import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Sora } from "next/font/google";
import { Toaster } from "sonner";

import "./globals.css";

import { QueryProvider } from "@/providers/query-provider";
import { AuthInitializer } from "@/modules/auth/components/auth-initializer";
import { ThemeProvider } from "@/components/providers/theme-provider";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin", "vietnamese"],
  variable: "--font-jakarta",
  display: "swap",
});

const sora = Sora({
  subsets: ["latin", "latin-ext"],
  variable: "--font-sora",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      suppressHydrationWarning
      className={`${jakarta.variable} ${sora.variable}`}
    >
      <body>
        <ThemeProvider>
          <QueryProvider>
            <AuthInitializer />

            {children}

            <Toaster
              richColors
              position="top-right"
            />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}